### ISSUE TITLE
2.0 namespaces

### ISSUE THREAD

**Issue by mickaelperrin** [Wabel/zoho-crm-client-wrapper#6]
Hi,

I have created [a new branch 2.0 on my fork](https://github.com/mickaelperrin/zoho-crm-client-wrapper/tree/2.0) that updates the namespaces.

Should I send a pull request to your 1.2 branch or would you prefer creating a new 2.0 branch ?

Thanks,

**Comment by rbergDrox** [comment]
Hi @mickaelperrin ,
Thank you. You have to send a pull request for this package  on 1.2 branch. I will update the build testing to check and valid your PR for zoho-orm package

**Comment by mickaelperrin** [comment]
Thanks, done !
